#!/usr/bin/env python3
"""N requests at once to one server, the same sampling for every runtime.

    concurrency_probe.py --url http://127.0.0.1:18600 --api eullm \
        --model qwen3-8b --concurrency 16 --profiles none,ollama,llama

Prints one line per round (profile, repeat) with the aggregate tokens per
second: every token generated by the round over its wall time, from the
moment all N requests are sent to the moment the last one answers.

WHY. c07 measured EuLLM 11-36% below llama-server at 16 concurrent
requests, and equal at one. Its requests set no sampling options, so each
server sampled with its own defaults: EuLLM Ollama's (repeat_penalty 1.1),
llama-server its own (repeat penalty off). With the penalty on, llama.cpp
looks up every one of the vocabulary's ~151k candidates in the penalty's
table, for every token of every sequence, on one CPU thread. The profiles
tell the two causes apart: `none` is what c07 measured, `ollama` and
`llama` give both servers the same chain.

The prompt is raw text on both (no chat template), the same for every
request, as in c07.
"""

from __future__ import annotations

import argparse
import json
import sys
import threading
import time
import urllib.request

PROMPT = "Write a long, detailed story about a lighthouse keeper on a remote island.\n\n"

# Each server's defaults, written out, so either server can be given the other's.
PROFILES = {
    "none": None,  # no options: the server's own defaults (what c07 measured)
    "ollama": {"temperature": 0.8, "top_k": 40, "top_p": 0.9, "min_p": 0.0,
               "repeat_penalty": 1.1, "repeat_last_n": 64},
    "llama": {"temperature": 0.8, "top_k": 40, "top_p": 0.95, "min_p": 0.05,
              "repeat_penalty": 1.0, "repeat_last_n": 64},
    "greedy": {"temperature": 0.0, "top_k": 1, "repeat_penalty": 1.0},
}


def body(api: str, model: str, sampling, num_predict: int, seed: int) -> tuple:
    """(path, JSON body) of one request."""
    if api == "eullm":
        options = dict(sampling or {}, num_predict=num_predict, seed=seed)
        return "/api/generate", {"model": model, "prompt": PROMPT, "raw": True,
                                 "stream": False, "think": False, "options": options}
    return "/completion", dict(sampling or {}, prompt=PROMPT, n_predict=num_predict,
                               seed=seed, stream=False, cache_prompt=True)


def generated(api: str, answer: dict) -> int:
    if api == "eullm":
        return int(answer.get("eval_count") or 0)
    return int(answer.get("tokens_predicted") or 0)


def post(url: str, path: str, payload: dict, timeout: float) -> dict:
    req = urllib.request.Request(url + path, data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read())


def one_round(args, sampling, rnd: int) -> dict:
    results = [None] * args.concurrency
    start = threading.Barrier(args.concurrency + 1)

    def worker(i):
        path, payload = body(args.api, args.model, sampling, args.num_predict, 1000 * rnd + i)
        start.wait()
        t0 = time.time()
        try:
            answer = post(args.url, path, payload, args.timeout)
            results[i] = (generated(args.api, answer), time.time() - t0, None)
        except Exception as e:  # noqa: BLE001 - every failure is reported, none hidden
            results[i] = (0, time.time() - t0, str(e)[:200])

    threads = [threading.Thread(target=worker, args=(i,)) for i in range(args.concurrency)]
    for t in threads:
        t.start()
    start.wait()
    t0 = time.time()
    for t in threads:
        t.join()
    wall = time.time() - t0
    tokens = sum(r[0] for r in results)
    errors = [r[2] for r in results if r[2]]
    return {"tokens": tokens, "wall_s": round(wall, 3),
            "agg_tok_s": round(tokens / wall, 1) if wall > 0 else None,
            "per_request_tok_s": round(sum(r[0] / r[1] for r in results if r[1] > 0)
                                       / len(results), 1),
            "errors": errors[:3], "failed": len(errors)}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--url", required=True)
    ap.add_argument("--api", choices=("eullm", "llama"), required=True)
    ap.add_argument("--model", required=True)
    ap.add_argument("--label", default="", help="a name for the server, printed on every line")
    ap.add_argument("--concurrency", type=int, required=True)
    ap.add_argument("--profiles", default="none,ollama,llama")
    ap.add_argument("--num-predict", type=int, default=256)
    ap.add_argument("--repeats", type=int, default=2)
    ap.add_argument("--timeout", type=float, default=900)
    args = ap.parse_args(argv)

    # One short request first: the model loads, and nothing measured pays for it.
    path, payload = body(args.api, args.model, None, 8, 0)
    post(args.url, path, payload, args.timeout)

    for name in args.profiles.split(","):
        if name not in PROFILES:
            print(f"unknown profile {name!r}: one of {', '.join(PROFILES)}", file=sys.stderr)
            return 2
        for rnd in range(args.repeats):
            r = one_round(args, PROFILES[name], rnd)
            print(json.dumps(dict({"label": args.label or args.api, "profile": name,
                                   "concurrency": args.concurrency, "repeat": rnd}, **r)),
                  flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
